{
    'name': 'GM POS REPORT',
    'version': '17.0.1.0.0',
    'category': 'Point of Sale',
    'sequence': 1,
    'summary': """Belong to GM""",
    'author': 'GM',
    'company': 'GM',
    'maintainer': 'GM',
    'website': "",
    'depends': ['base', 'sale', 'stock', 'point_of_sale', 'account', 'salesperson_pos_order_line'],
    'data': [
        'security/ir.model.access.csv',
        'views/sales_report_view.xml',
        'views/sales_report_menu_view.xml',
        'views/report_layout_templates.xml',
        'views/sales_report_pdf.xml',
        'views/portal_templates.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}