{
    'name': 'GM x POS',
    'version': '17.0.1.0.0',
    'category': 'Point of Sale',
    'sequence': 1,
    'summary': """Belong to GM x POS""",
    'author': 'GM x POS',
    'company': '',
    'maintainer': '',
    'website': "",
    'depends': ['base', 'sale', 'stock', 'point_of_sale', 'account', 'mrp', 'loyalty', 'pos_loyalty', 'purchase', 'hr', 'l10n_id', 'l10n_id_efaktur', 'pos_sale'], #, 'l10n_id_efaktur_coretax'
    'data': [
        # 'security/hr_security.xml',
        'security/return_approval_security.xml',
        'security/res_partner_record_rules.xml',
        'security/ir.model.access.csv',
        'data/mrp_bom_schedule.xml',
        'data/sequence.xml',
        'data/return_approval_sequence.xml',
        'views/return_approval_wizard.xml',
        'views/return_approval_view.xml',
        'views/views_pos_order.xml',
        'views/views_stock_picking.xml',
        'views/views_res_partner.xml',
        'views/views_account_move.xml',
        'views/views_account_payment.xml',
        'views/views_log_code_runtime.xml',
        'views/views_log_note.xml',
        'views/menu_log_note.xml',
        'views/views_pos_session.xml',
        'views/ir_sequence_view.xml',
        'views/product_template_view.xml',
        'views/views_store_warehouse.xml',
        # 'views/views_master_type.xml',
        'views/views_master_configuration.xml',
        'views/menu_master_configuration.xml',
        'views/views_manual_sync_ss_to_mc.xml',
        'views/views_loyalty_program.xml',
        'views/views_manual_sync_mc_to_ss.xml',
        'views/views_loyalty_rule.xml',
        'views/views_loyalty_reward.xml',
        'views/views_product_pricelist.xml',
        'views/views_purchase_order.xml',
        'views/views_token_generate.xml',
        'views/views_list_license.xml',
        'views/pos_category_view.xml',
        'views/stock_picking_type_view.xml',
        'views/uom_category_view.xml',
        'views/uom_uom_view.xml',
        'views/views_account_tax_repartition_line.xml',
        'views/views_account_tax.xml',
        'views/views_product_category.xml',
        # 'views/views_product_pricelist_item.xml',
        'views/views_res_partner_title.xml',
        # 'views/pos_config_view.xml',
        'views/pos_payment_method_views.xml',
        'views/hr_employee_view.xml',
        'views/loyalty_card_view.xml',
        'views/account_journal_view.xml',
        'views/account_account_view.xml',
        'views/pos_orderline_views.xml',
        # 'views/inventory_stock_view.xml',
        'views/barcode_config_views.xml',
        'views/print_barcode_view.xml',
        'views/product_product_view.xml',
        'views/mrp_unbuild_line_view.xml',
        'views/pos_timbangan_views.xml',
        'views/report_stock_view.xml',
        'views/customer_group_view.xml',
        'views/res_config_settings_view.xml',
        'views/proforma_report.xml',
        'views/qty_on_hand.xml',
        # 'views/rounding_pos.xml',
        'views/sale_order_view.xml',
        'views/report_invoice_line_number.xml',
        'views/paper_format_a5.xml',
        'views/sale_order_wizard_pin.xml',
        'views/mapping_tax_sap_view.xml',
        # 'views/report_faktur_pajak_a5_action.xml',
        # 'views/report_faktur_pajak_template.xml',
        'views/transfer_stock_report.xml',
        'views/rounding_quotation.xml',
        # 'reports/sales_report_menu_view.xml',
        # 'reports/report_layout_templates.xml',
        # 'reports/sales_report_pdf.xml',
        # 'reports/portal_templates.xml',
    ],
    'assets': {
        'point_of_sale._assets_pos': [
            'dev_pos/static/src/xml/pos_dp_paymentline.xml',
            'dev_pos/static/src/xml/remove_delete_button_payment.xml',
            'dev_pos/static/src/xml/back_button.xml',
            'dev_pos/static/src/xml/invoice_number.xml',
            'dev_pos/static/src/js/pos_session_load.js',
            'dev_pos/static/src/js/coupon_frontend.js',
            'dev_pos/static/src/js/pos_dp_productscreen.js',
            'dev_pos/static/src/js/pos_dp_payment.js',
            'dev_pos/static/src/js/pos_dp_paymentline.js',
            'dev_pos/static/src/js/pos_dp_validate.js',
            'dev_pos/static/src/js/pos_sale_order.js',
            'dev_pos/static/src/js/struk_pelunasan.js',
            'dev_pos/static/src/js/pos_custom_patch.js',
            'dev_pos/static/src/js/product_screen_patch.js',
            'dev_pos/static/src/js/remaining_amount_animation.js',
            'dev_pos/static/src/js/remove_delete_button_payment.js',
            'dev_pos/static/src/js/rounding_pos.js',
            'dev_pos/static/src/js/rounding_delete.js',
            'dev_pos/static/src/js/invoice_number.js',
            'dev_pos/static/src/js/notes_button.js',
            'dev_pos/static/src/js/sale_order_list.js',
            'dev_pos/static/src/js/gift_card_auto_customer.js',
            # 'dev_pos/static/src/js/quantity_lock.js',
        ],
        'web.assets_backend': [
            'dev_pos/static/src/xml/button_generate_report.xml',
            'dev_pos/static/src/xml/generete_gift_cards.xml',
            'dev_pos/static/src/js/button_generate_report.js',
            'dev_pos/static/src/js/sale_order_warehouse.js',
            'dev_pos/static/src/js/sale_order_wizard.js',
        ],
    },
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}